#!/usr/bin/env bash
# Regenerates src/generated/ from the installed codex binary.
#
#   harness/codex/scripts/gen-types.sh [codex-bin]
#
# Runs `codex app-server generate-ts` (stable API only, no --experimental) into a
# temp dir, then vendors only the transitive closure of the root types listed
# below, rewriting relative imports to NodeNext-style `.js` specifiers. The codex
# version is recorded in src/generated/version.ts; bump SUPPORTED_CODEX_VERSIONS
# in src/version.ts after checking the diff.
set -euo pipefail

here="$(cd "$(dirname "$0")/.." && pwd)"
codex="${1:-codex}"
out="$here/src/generated"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

version="$("$codex" --version | awk '{print $NF}')"
"$codex" app-server generate-ts --out "$tmp" >/dev/null

rm -rf "$out"
mkdir -p "$out"

# Root types the adapter imports. Everything they reference is pulled in.
ROOTS="
InitializeParams InitializeResponse RequestId ReasoningEffort MessagePhase
v2/ThreadStartParams v2/ThreadStartResponse v2/ThreadResumeParams v2/ThreadResumeResponse
v2/ThreadUnsubscribeParams v2/ThreadUnsubscribeResponse
v2/TurnStartParams v2/TurnStartResponse v2/TurnSteerParams v2/TurnSteerResponse
v2/TurnInterruptParams v2/TurnInterruptResponse
v2/ThreadItem v2/Turn v2/TurnError v2/CodexErrorInfo v2/UserInput v2/ThreadStatus
v2/SandboxMode v2/SandboxPolicy v2/AskForApproval v2/ApprovalsReviewer
v2/ErrorNotification v2/ThreadStatusChangedNotification v2/ThreadClosedNotification
v2/ThreadTokenUsageUpdatedNotification v2/TurnStartedNotification v2/TurnCompletedNotification
v2/TurnDiffUpdatedNotification v2/TurnPlanUpdatedNotification
v2/ItemStartedNotification v2/ItemCompletedNotification v2/AgentMessageDeltaNotification
v2/CommandExecutionOutputDeltaNotification v2/ReasoningSummaryTextDeltaNotification
v2/ReasoningTextDeltaNotification v2/McpToolCallProgressNotification
v2/ServerRequestResolvedNotification v2/WarningNotification v2/ModelReroutedNotification
v2/CommandExecutionRequestApprovalParams v2/CommandExecutionRequestApprovalResponse
v2/FileChangeRequestApprovalParams v2/FileChangeRequestApprovalResponse
v2/PermissionsRequestApprovalParams v2/PermissionsRequestApprovalResponse
v2/ToolRequestUserInputParams v2/ToolRequestUserInputResponse
v2/McpServerElicitationRequestParams v2/McpServerElicitationRequestResponse
"

node - "$tmp" "$out" $ROOTS <<'EOF'
const fs = require('node:fs');
const path = require('node:path');
const [src, out, ...roots] = process.argv.slice(2);
const seen = new Set();
const queue = roots.map((r) => r + '.ts');
while (queue.length) {
  const rel = path.normalize(queue.pop());
  if (seen.has(rel)) continue;
  seen.add(rel);
  const text = fs.readFileSync(path.join(src, rel), 'utf8');
  for (const m of text.matchAll(/from "(\.{1,2}\/[^"]+)"/g)) queue.push(path.join(path.dirname(rel), m[1] + '.ts'));
}
for (const rel of [...seen].sort()) {
  const text = fs.readFileSync(path.join(src, rel), 'utf8').replace(/from "(\.{1,2}\/[^"]+)"/g, 'from "$1.js"');
  fs.mkdirSync(path.dirname(path.join(out, rel)), { recursive: true });
  fs.writeFileSync(path.join(out, rel), text);
}
console.error(`vendored ${seen.size} files`);
EOF

cat >"$out/version.ts" <<EOF
// GENERATED by scripts/gen-types.sh. Do not edit.
/** codex-cli version these types were generated from (\`codex app-server generate-ts\`). */
export const CODEX_GENERATED_VERSION = '$version';
EOF
echo "generated from codex-cli $version"
